# Generated by Django 4.2.4 on 2023-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=5)),
                ('container_status', models.CharField(choices=[('IN', 'In Warehouse'), ('OUT', 'Out of Warehouse')], max_length=3)),
                ('container_location', models.CharField(choices=[('TX', 'Austin, Texas'), ('CA', 'San Francisco, California'), ('NY', 'New York City, New York'), ('IL', 'Chicago, Illinois'), ('WA', 'Seattle, Washington'), ('MA', 'Boston, Massachusetts'), ('GA', 'Atlanta, Georgia'), ('CO', 'Denver, Colorado'), ('FL', 'Miami, Florida'), ('DC', 'Washington, D.C.'), ('PA', 'Philadelphia, Pennsylvania'), ('AZ', 'Phoenix, Arizona'), ('MI', 'Detroit, Michigan'), ('OH', 'Columbus, Ohio')], max_length=2)),
                ('container_eta', models.DateField(default='Not Out of Warehouse')),
            ],
        ),
    ]
